### ISSUE TITLE
InfluxDB: Do type conversion in the publisher

### ISSUE THREAD

**Issue by bradjc** [lab11/gateway#11]
In case a parse.js file does something stupid.

**Comment by ppannuto** [comment]
How? There's no way to know what types should be, guessing with exceptions
is error prone:

Now it will commit that data type as a float and you can never send "no one
here"?

I don't think we should rely on hacks for broken data sources

**Comment by bradjc** [comment]
I would agree with you 100% but because you can't fix it after-the-fact I'm not so sure.

**Comment by brghena** [comment]
Why can't you run a test on whether the data, if a string, is a int or
float?
http://stackoverflow.com/questions/175739/is-there-a-built-in-way-in-javascript-to-check-if-a-string-is-a-valid-number

Thanks
Branden Ghena
PhD Student - University of Michigan
Computer Science and Engineering

**Comment by ppannuto** [comment]
Feels like it would be hard get that right. Maybe there's a library that
does it?

Also Branden why did you thank me in that email?

**Comment by bradjc** [comment]
Upon further review, I think we _have_ to hack for broken parse.js files. Because if `powerblade` and `superblade` both want to publish on the key 'power', and one uses a string instead of a number, the one that gets in first will set the data type and the other will never be able to store its data.

**Comment by bradjc** [comment]
@ppannuto take a gander at f8a94a4d1c12b88c612161e507a1acaf450bc962

I think @brghena and I did enough checking that it should be right. We even tested it for a minute. And pushed to master #safetyoff
